### ISSUE TITLE
Javascript for form validation on add-form-valiodation branch

### ISSUE THREAD

**Issue by see-why** [Hector096/My-Portfolio#15]
Great job so far, it seems your [javascript logic](https://github.com/Hector096/My-Portfolio/blob/add-form-validation/app.js#L37-L47) does not seem to work properly.

Kindly take a second look at it, you can use the browser developer tools to debug it, remember to remove any console.logs after debugging.

**Comment by Hector096** [comment]
Thanks for the Review, Ill be looking into it.
